version: "3.8"

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: [ "mkdocs", "serve", "--dev-addr=0.0.0.0:8080" ]
