site_name: DeepExtension Documentation
site_url: https://docs.deepextension.ai
theme:
  name: material
  logo: assets/images/LOGO-White.svg
  favicon: assets/images/favicon.svg
  language: en
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy
    - content.action.edit
    - i18n
  palette:
    primary: blue #'#0a1a35' #'#07142A'
#  name: readthedocs
#  highlightjs: true

nav:
  - Introduction:
      - Overview: index.md
      - Key Concepts: intro/key-concepts.md
      - Product Architecture: intro/architecture.md
  - Getting Started: getting-started/quick-start.md
#      - Installation:
#          - Ubuntu (CUDA): getting-started/install-ubuntu.md
#          - MacOS: getting-started/install-macos.md
  - User Guide:
      - UI Overview: user-guide/ui-overview.md
#      - Dashboard: user-guide/dashboard.md
      - DeepPrompt: user-guide/deep-prompt.md
      - Dataset Management: user-guide/dataset-management.md
      - Knowledge Base (RAG): user-guide/document-embedding.md
      - Model Training: user-guide/model-training.md
      - Model Assessment: user-guide/model-assessment.md
      - Model Management:
          - Third-party Models: user-guide/thirdparty-models.md
          - Base Models: user-guide/base-models.md
          - Trained Models: user-guide/trained-models.md
          - Saved Models: user-guide/saved-models.md
          - Deployed Models: user-guide/deployed-models.md
      - Setting:
          - Deployment Tool Configuration : user-guide/deployment-tool-configuration.md
          - Training Method Management : user-guide/training-methods.md
          - User Management : user-guide/user-management.md
  - Tutorials:
      - Overview: tutorials/overview.md
      - Process Dependency: tutorials/tutorial-process-dependency.md
      - "Quick Start: Run Your First Training": tutorials/tutorial-quick-start.md
  - Developer Guide:
      - Overview: developer/overview.md
      - Supported AI Platform & Why It Matters: developer/ai-platform-overview.md 
      - Installation Guide: developer/install.md
      - Add Base Models: developer/how-to-add-base-models.md 
      - Implement Customized Training (CUDA):
          - How You Implement Own Training (CUDA): developer/implement-own-ai-training-cuda.md
          - How We Implemented SFT-Demo and GRPO-Demo (CUDA): developer/implement-sft-grpo-demo.md
      - Implement Your Own Training (MacOS):
          - How You Implement Own Training (MacOS): developer/implement-own-ai-training-mac.md
          - How We Implemented MLX-Demo (MacOS): developer/implement-mlx-demo.md
  - Deployment & Ops:
      - Ollama as Deployment Tool: deployment/ollama-deployment.md
  - FAQ: faq.md
  - Release Notes: changelog.md
  - About & Support:
      - About Us: about/about-us.md
      - Acknowledgement: about/acknowledgement.md
      - Contact & Support: about/support.md
#  - Temp:
#      - Temp Page: post/how-agents-work-as-team.md
plugins:
  - search
  - i18n:
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: de
          name: Deutsch
          build: true
          site_name: DeepExtension Dokumentation
          nav_translations:
            Introduction: Einführung
            Overview: Übersicht
            "Key Concepts": "Zentrale Konzepte"
            "Product Architecture": "Architektur"

            Getting Started: Erste Schritte
            "Quick Start Guide": Schnellstart-Anleitung
            Installation: Installation
            "Ubuntu (CUDA)": Ubuntu (CUDA)
            MacOS: macOS

            User Guide: Benutzerhandbuch
            "UI Overview": UI-Übersicht
            #    Dashboard: Dashboard
            DeepPrompt: DeepPrompt
            "Model Training": Modelltraining
            "Dataset Management": Datensatzverwaltung
            "Knowledge Base (RAG)": Wissensdatenbank (RAG)
            "Model Assessment": Modellauswertung
            "Model Management": Modellverwaltung
            "Third-party Models": Drittanbieter-Modelle
            "Base Models": Basismodelle
            "Trained Models": Trainierte Modelle
            "Saved Models": Gespeicherte Modelle
            "Deployed Models": Bereitgestellte Modelle

            Setting: Einstellungen
            "Deployment Tool Configuration": Bereitstellungskonfiguration
            "Training Method Management": Trainingsmethodenverwaltung
            "User Management": Benutzerverwaltung

            Tutorials: Tutorials
            Overview: Überblick
            "Process Dependency": Prozessabhängigkeiten
            "Quick Start: Run Your First Training": "Schnellstart: Erstes Training durchführen"

            "Developer Guide": Entwicklerhandbuch
            Overview: Übersicht
            "Supported AI Platform & Why It Matters": Unterstützte KI-Plattformen & deren Bedeutung
            "Installation Guide": Installationsanleitung
            "Add Base Models": Basismodelle hinzufügen
            "Implement Your Own Training (CUDA)": Eigenes Training implementieren (CUDA)
            "Implement Your Own Training (MacOS)": Eigenes Training implementieren (macOS)

            "Implement Customized Training (CUDA)": Angepasstes Training implementieren (CUDA)
            "How You Implement Own Training (CUDA)": So implementieren Sie eigenes Training (CUDA)
            "How We Implemented SFT-Demo and GRPO-Demo (CUDA)": So haben wir SFT- und GRPO-Demo implementiert (CUDA)
            "Implement Your Own Training (MacOS)": Eigenes Training implementieren (macOS)
            "How You Implement Own Training (MacOS)": So implementieren Sie eigenes Training (macOS)
            "How We Implemented MLX-Demo (MacOS)": So haben wir die MLX-Demo implementiert (macOS)


            "Deployment & Ops": Bereitstellung & Betrieb
            "Ollama as Deployment Tool": Ollama als Bereitstellungswerkzeug

            FAQ: FAQ
            "Release Notes": Versionshinweise

            "About & Support": Über & Support
            "About Us": Über uns
            "Acknowledgement": Danksagung
            "Contact & Support": Kontakt & Support
        - locale: zh
          name: 中文
          build: true
          site_name: DeepExtension 文档
          nav_translations:
            Introduction: 介绍
            Overview: 概览
            "Key Concepts": "核心概念"
            "Product Architecture": "产品架构"
            Getting Started: 入门指南
            "Quick Start Guide": 快速开始
            Installation: 安装
            "Ubuntu (CUDA)": Ubuntu（CUDA）
            MacOS: MacOS

            User Guide: 用户指南
            "UI Overview": UI 总览
            #    Dashboard: 控制面板
            DeepPrompt: DeepPrompt
            "Model Training": 模型训练
            "Dataset Management": 数据集管理
            "Knowledge Base (RAG)": 知识库（RAG）
            "Model Assessment": 模型评估
            "Model Management": 模型管理
            "Third-party Models": 第三方模型
            "Base Models": 基础模型
            "Trained Models": 已训练模型
            "Saved Models": 已保存模型
            "Deployed Models": 已部署模型

            Setting: 系统设置
            "Deployment Tool Configuration": 部署工具配置
            "Training Method Management": 训练方法管理
            "User Management": 用户管理

            Tutorials: 教程
            "Overview": 教程概览
            "Process Dependency": 流程依赖
            "Quick Start: Run Your First Training": 快速上手：运行你的第一个训练

            "Developer Guide": 开发者指南
            "Overview": 概览
            "Supported AI Platform & Why It Matters": 支持的 AI 平台及其意义
            "Installation Guide": 安装指南
            "Add Base Models": 添加基础模型
            "Implement Your Own Training (CUDA)": 实现自定义训练（CUDA）
            "Implement Your Own Training (MacOS)": 实现自定义训练（MacOS）

            "Implement Customized Training (CUDA)": 实现自定义训练（CUDA）
            "How You Implement Own Training (CUDA)": 您的自定义训练实现方式（CUDA）
            "How We Implemented SFT-Demo and GRPO-Demo (CUDA)": 我们如何实现SFT和GRPO演示（CUDA）
            "Implement Your Own Training (MacOS)": 自定义训练实现（MacOS）
            "How You Implement Own Training (MacOS)": 您的自定义训练实现方式（MacOS）
            "How We Implemented MLX-Demo (MacOS)": 我们如何实现MLX演示（MacOS）

            "Deployment & Ops": 部署与运维
            "Ollama as Deployment Tool": 使用 Ollama 部署模型

            FAQ: 常见问题
            "Release Notes": 更新日志

            "About & Support": 关于与支持
            "About Us": 关于我们
            "Acknowledgement": 鸣谢
            "Contact & Support": 联系与支持
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - markdown_include.include:
      base_path: .
  - codehilite
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - toc:
      permalink: true
#  - pymdownx.copybutton

# nav_translations:
#   de:
#     Introduction: Einführung
#     Overview: Übersicht
#   zh:
#     Introduction: 介绍
#     Overview: 概览
  #    - Key Concepts: intro/key-concepts.md
  #     - Product Architecture: intro/architecture.md
  # - Getting Started:
  #     - Quick Start Guide: getting-started/quick-start.md
  #     - Installation:
  #         - Ubuntu (CUDA): getting-started/install-ubuntu.md
  #         - macOS: getting-started/install-macos.md
  # - User Guide:
  #     - UI Overview: user-guide/ui-overview.md
  #     - UI Dashboard: user-guide/ui-dashboard.md
  #     - DeepPrompt: user-guide/deep-prompt.md
  #     - Model Training: user-guide/model-training.md
  #     - Datasets Management: user-guide/dataset-management.md
  #     - Document Embedding: user-guide/document-embedding.md
  #     - Model Assessment: user-guide/model-assessment.md
  #     - Model Management:
  #         - Thirdparty Models: user-guide/thirdparty-models.md
  #         - Base Models: user-guide/base-models.md
  #         - Tranined Models: user-guide/trained-models.md
  #         - Saved Models: user-guide/saved-models.md
  #         - Deployed Models: user-guide/deployed-models.md
  #     - Setting:
  #         - Training Method Management : user-guide/training-methods.md
  #         - User Management : user-guide/user-management.md
  # - Tutorials:
  #     - First End-to-End Workflow: tutorials/e2e.md
  #     - Custom Model Fine-Tuning: tutorials/custom-finetune.md
  #     - Integration with Existing Tools: tutorials/integration.md
  # - Developer Guide:
  #     - API Overview: developer/api-overview.md
  #     - Authentication & Tokens: developer/auth.md
  #     - Data & Training APIs: developer/data-apis.md
  #     - Deployment APIs: developer/deploy-apis.md
  #     - Custom Plugin Development: developer/plugins.md
  #     - Webhooks & Events: developer/webhooks.md
  # - Deployment & Ops:
  #     - System Requirements: ops/system-reqs.md
  #     - Configuration Options: ops/config.md
  #     - Logging & Monitoring: ops/logging.md
  #     - Backup & Recovery: ops/backup.md
  #     - Upgrading: ops/upgrade.md
  # - FAQ: faq.md
  # - Release Notes: changelog.md
  # - About & Support:
  #     - About the Team: about/team.md
  #     - Contact & Support: about/support.md

# nav_translations:
#   de:
#     - Einführung:
#         - Übersicht: index.md
    #     - Zentrale Konzepte: intro/key-concepts.md
    #     - Architektur: intro/architecture.md
    # - Erste Schritte:
    #     - Schnellstart: getting-started/quick-start.md
    #     - Installation:
    #         - Ubuntu (CUDA): getting-started/install-ubuntu.md
    #         - macOS: getting-started/install-macos.md
    # - Benutzerhandbuch:
    #     - UI Überblick: user-guide/ui-overview.md
    #     - Datenverwaltung: user-guide/dataset-management.md
    #     - Trainingspipelines: user-guide/training-pipelines.md
    #     - Modellbereitstellung: user-guide/deployment.md
    #     - Lebenszyklus-Management: user-guide/lifecycle.md
    #     - Wissensdatenbank & Prompt-Frontend: user-guide/kb-prompt.md
    # - Tutorials:
    #     - Erster End-to-End Workflow: tutorials/e2e.md
    #     - Modell-Feinabstimmung: tutorials/custom-finetune.md
    #     - Integration mit bestehenden Tools: tutorials/integration.md
    # - Entwicklerhandbuch:
    #     - API Überblick: developer/api-overview.md
    #     - Authentifizierung & Tokens: developer/auth.md
    #     - Daten- & Trainings-APIs: developer/data-apis.md
    #     - Bereitstellungs-APIs: developer/deploy-apis.md
    #     - Plugin-Entwicklung: developer/plugins.md
    #     - Webhooks & Events: developer/webhooks.md
    # - Betrieb & Bereitstellung:
    #     - Systemanforderungen: ops/system-reqs.md
    #     - Konfigurationsoptionen: ops/config.md
    #     - Logging & Monitoring: ops/logging.md
    #     - Backup & Wiederherstellung: ops/backup.md
    #     - Aktualisierung: ops/upgrade.md
    # - FAQ: faq.md
    # - Versionshinweise: changelog.md
    # - Über & Support:
    #     - Über das Team: about/team.md
    #     - Kontakt & Support: about/support.md

  # zh:
  #   - 简介:
  #       - 概览: index.md
    #     - 核心概念: intro/key-concepts.md
    #     - 产品架构: intro/architecture.md
    # - 快速开始:
    #     - 快速指南: getting-started/quick-start.md
    #     - 安装:
    #         - Ubuntu（CUDA）: getting-started/install-ubuntu.md
    #         - macOS: getting-started/install-macos.md
    # - 用户指南:
    #     - UI总览: user-guide/ui-overview.md
    #     - 数据集管理: user-guide/dataset-management.md
    #     - 训练流程: user-guide/training-pipelines.md
    #     - 模型部署: user-guide/deployment.md
    #     - 生命周期管理: user-guide/lifecycle.md
    #     - 知识库与 Prompt 前端: user-guide/kb-prompt.md
    # - 教程:
    #     - 第一个端到端工作流: tutorials/e2e.md
    #     - 自定义模型微调: tutorials/custom-finetune.md
    #     - 与现有工具集成: tutorials/integration.md
    # - 开发者指南:
    #     - API 总览: developer/api-overview.md
    #     - 鉴权与令牌: developer/auth.md
    #     - 数据与训练 API: developer/data-apis.md
    #     - 部署 API: developer/deploy-apis.md
    #     - 插件开发: developer/plugins.md
    #     - Webhooks 与事件: developer/webhooks.md
    # - 运维部署:
    #     - 系统要求: ops/system-reqs.md
    #     - 配置选项: ops/config.md
    #     - 日志与监控: ops/logging.md
    #     - 备份与恢复: ops/backup.md
    #     - 升级: ops/upgrade.md
    # - 常见问题: faq.md
    # - 更新日志: changelog.md
    # - 关于与支持:
    #     - 团队介绍: about/team.md
    #     - 联系与支持: about/support.md
